services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: afifa-expense-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - afifa-expense

    db:
        image: postgres:15
        container_name: afifa-expense-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5438:${DB_PORT}"
        volumes:
            - content:/var/lib/postgresql/data
        networks:
            - afifa-expense

    nginx:
        image: nginx:alpine
        container_name: afifa-expense-nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - afifa-expense

volumes:
    content:

networks:
    afifa-expense:
        driver: bridge
